# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Unit', models.CharField(max_length=250)),
                ('Quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Prep_Time', models.FloatField()),
                ('Cook_Time', models.FloatField()),
                ('Serves', models.FloatField()),
                ('Method', models.CharField(max_length=250)),
                ('Notes', models.CharField(max_length=250)),
                ('Image', models.EmailField(max_length=254)),
                ('Deleted', models.BooleanField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Category')),
            ],
        ),
        migrations.AddField(
            model_name='ingredent',
            name='Recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
