# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Cook_Time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Prep_Time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Cook_Time_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Cook_Time_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Prep_Time_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Prep_Time_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Image',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Serves',
            field=models.FloatField(default=0),
        ),
    ]
