# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20171031_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredent',
            old_name='Recipe_id',
            new_name='Recipe',
        ),
    ]
