# Generated by Django 2.1.4 on 2019-04-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20190112_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Image',
            field=models.ImageField(null=True, upload_to='photo_files/thumbnails'),
        ),
    ]
