# Generated by Django 2.1.4 on 2019-04-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20190410_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Cook_Time_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Cook_Time_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Prep_Time_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Prep_Time_min',
            field=models.IntegerField(default=0),
        ),
    ]
