# Generated by Django 2.1.4 on 2019-04-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20190410_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Image',
            field=models.ImageField(null=True, upload_to='photo_files/original'),
        ),
    ]
